VAGRANTFILE_API_VERSION = "2"

$script = <<SCRIPT
sudo apt-get update
sudo apt-get install -y nginx
sudo service nginx start
SCRIPT

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = "debian-jessie"

    config.vm.provision "shell",
        inline: $script
end
